// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApG4OrlY16hJerIEo6mpfz72voI_L3Ntk',
    appId: '1:676309974495:android:6b3f3375d6d2bc5af7586a',
    messagingSenderId: '676309974495',
    projectId: 'examplechat2023',
    databaseURL: 'https://examplechat2023-default-rtdb.firebaseio.com',
    storageBucket: 'examplechat2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZlyHj4crDXFyl2QHTscq7d2_jV2Bv9k4',
    appId: '1:676309974495:ios:e5b44d4c0421ee72f7586a',
    messagingSenderId: '676309974495',
    projectId: 'examplechat2023',
    databaseURL: 'https://examplechat2023-default-rtdb.firebaseio.com',
    storageBucket: 'examplechat2023.appspot.com',
    androidClientId: '676309974495-9gqlv89vf4qcs8l5ntgt9adkbep3tk8v.apps.googleusercontent.com',
    iosClientId: '676309974495-l2t4lul8d4ppbjs1luneagdh164cciev.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatExample',
  );
}
